### ISSUE TITLE
Implement changes in 'fix-path-class' into all branches

### ISSUE THREAD

**Issue by pauloalbert** [DanKatzuv/BaseBot#25]
split each branch into a fix-branch and fix all problems when using getWaypoint() and Vector.add() in the code.

* you could simply do this by removing each respective method, seeing where errors are caused and checking each case where that method is called.

**Comment by DanKatzuv** [comment]
Please rethink if this is a must because it seems a lot of work. Another point of consideration is using `git cherry-pick` on every branch, which looks like a classic use here.

**Comment by pauloalbert** [comment]
I think this is necessary. On our last work day we spent hours trying to convert a basic algorithm into our code, but got incorrect results each time until we scrapped our work and used basic arrays.

The alternation between methods creating a new instance and methods returning the same instance is unclear. It needs to be globally set to one of the two and fixed in all our methods before we rely on this sample in future projects.
